name: Build source distribution

on: [push, pull_request]

jobs:
  build:
    name: Source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive --depth=1

      - name: Install tools and dependencies
        run: |
          sudo apt-get install -y python3-dev python3-pip python3-venv
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip build

      - name: Create source distribution
        run: |
          source venv/bin/activate
          python -m build --sdist --outdir dist/ .

      - uses: actions/upload-artifact@v1
        with:
          name: pymmcore-sdist
          path: dist
